# Generated by Django 5.0.6 on 2024-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sale',
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
